### ISSUE TITLE
obsctl context switch should list available options

### ISSUE THREAD

**Issue by bill3tt** [observatorium/obsctl#4]
```
❯ obsctl context switch
Error: accepts 1 arg(s), received 0
Usage:
  obsctl context switch [flags]

Flags:
  -h, --help   help for switch

Global Flags:
      --log.format string   Log format to use. (default "clilog")
      --log.level string    Log filtering level. (default "info")
```

It would be nicer developer UX if the output of this command would show the values that would be accepted by obsctl. My alternative at the moment is manually inspecting the config file :shrug:

**Comment by saswatamcode** [comment]
Implemented this [here](https://github.com/observatorium/obsctl/pull/3/commits/c554f87166ea9e56f5ee27660aa08a836c6bb913). 🙂

**Comment by esnible** [comment]
The current message is wrong; the usage  is given as `obsctl context switch [flags]` when it should be `switch <api>/<tenant>`.
