### ISSUE TITLE
"make lint" fails

### ISSUE THREAD

**Issue by esnible** [observatorium/obsctl#44]
On my Mac:

```
make lint
...
>> verifying modules being imported
faillint: internal error: package "context" without types was imported from "github.com/observatorium/obsctl/pkg/config"
```

This is not a recent problem; I see the same thing with I check out early commits.

I see the same thing running `faillint-v1.8.0 ./...` manually.

**Comment by iblancasa** [comment]
@esnible you're using an old version of `faillint`. [Try with `1.11.0`](https://github.com/fatih/faillint/releases/tag/v1.11.0) and the error will not be there anymore :)

**Comment by saswatamcode** [comment]
I wasn't able to repro this, but it might be due to versions. We pin to v1.8.0 of faillint currently, so just running `bingo get github.com/fatih/faillint@v1.11.0` and `make lint` should work! 🙂

**Comment by esnible** [comment]
@saswatamcode I was able to get `make lint` working following your instructions.

I created a PR.  I created the PR by doing `bingo get github.com/fatih/faillint@v1.11.0` and checking in the work performed.
https://github.com/observatorium/obsctl/pull/46

I am not sure why that fixes it, or why you and @iblancasa cannot reproduce this.  It worked for me.  Perhaps faillint 1.8.0 doesn't work well on OSX?

**Comment by iblancasa** [comment]
I was able to reproduce it on Red Hat Linux

**Comment by iblancasa** [comment]
I'm on go1.18 too

**Comment by esnible** [comment]
```
go version
go version go1.18.2 darwin/amd64
```

**Comment by iblancasa** [comment]
```sh
$ go version
go version go1.18.4 linux/amd64
```

**Comment by saswatamcode** [comment]
For me,
```
go version go1.18.1 linux/amd64
```
